### ISSUE TITLE
Itembuilds suggestion isn't good to new players learn

### ISSUE THREAD

**Issue by Guizera9** [nine9123/Bleach-vs-One-Piece-Reborn#20]
Hey @nine9123 , looking to improve the suggestions of items to newcomers I've made changes at the suggestions, can we put it on?

Let's to update it

[default_antimage.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659789/default_antimage.txt)
[default_axe.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659790/default_axe.txt)
[default_bane.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659791/default_bane.txt)
[default_beastmaster.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659792/default_beastmaster.txt)
[default_bloodseeker.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659793/default_bloodseeker.txt)
[default_centaur.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659794/default_centaur.txt)
[default_doom_bringer.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659795/default_doom_bringer.txt)
[default_dragon_knight.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659796/default_dragon_knight.txt)
[default_drow_ranger.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659797/default_drow_ranger.txt)
[default_earthshaker.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659798/default_earthshaker.txt)
[default_elder_titan.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659799/default_elder_titan.txt)
[default_ember_spirit.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659800/default_ember_spirit.txt)
[default_enchantress.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659801/default_enchantress.txt)
[default_enigma.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659802/default_enigma.txt)
[default_huskar.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659803/default_huskar.txt)
[default_juggernaut.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659804/default_juggernaut.txt)
[default_keeper_of_the_light.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659805/default_keeper_of_the_light.txt)
[default_kunkka.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659806/default_kunkka.txt)
[default_lina.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659807/default_lina.txt)
[default_luna.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659808/default_luna.txt)
[default_lycan.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659809/default_lycan.txt)
[default_mirana.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659810/default_mirana.txt)
[default_naga_siren.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659811/default_naga_siren.txt)
[default_necrolyte.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659812/default_necrolyte.txt)
[default_night_stalker.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659813/default_night_stalker.txt)
[default_phantom_assassin.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659814/default_phantom_assassin.txt)
[default_phantom_lancer.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659815/default_phantom_lancer.txt)
[default_queenofpain.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659816/default_queenofpain.txt)
[default_riki.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659817/default_riki.txt)
[default_skeleton_king.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659818/default_skeleton_king.txt)
[default_slardar.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659819/default_slardar.txt)
[default_slark.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659820/default_slark.txt)
[default_sniper.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659821/default_sniper.txt)
[default_spectre.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659822/default_spectre.txt)
[default_sven.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659823/default_sven.txt)
[default_techies.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659824/default_techies.txt)
[default_templar_assassin.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659825/default_templar_assassin.txt)
[default_terrorblade.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659826/default_terrorblade.txt)
[default_troll_warlord.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659827/default_troll_warlord.txt)
[default_ursa.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659828/default_ursa.txt)
[default_vengefulspirit.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659829/default_vengefulspirit.txt)
[default_windrunner.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659830/default_windrunner.txt)
[default_zuus.txt](https://github.com/nine9123/Bleach-vs-One-Piece-Reborn/files/4659831/default_zuus.txt)

**Comment by Guizera9** [comment]
Earlier we put it on, earlier newcomers can use this to help them learn which items can help them better.

**Comment by nine9123** [comment]
This needs to be an pull request.
